name: bot
on:
    push:

jobs:
    BOT:
        runs-on: ubuntu-latest
        steps:
            - name: code
              uses: actions/checkout@v4

            - name: Setup Firefox
              uses: web-platform-tests/wpt-action@v1
              with:
                browser: firefox
                version: latest

            - name: install requirements
              run: pip install -r requirements.txt
            - name: run app
              run: python проход_по_группам_и_прожатие_участвоваеть.py
