name: bot
on:
    push:

jobs:
    BOT:
        runs-on: ubuntu-latest
        steps:
            - name: code
              uses: actions/checkout@v4
            - name: Load .env file
              uses: actions/load-environment-variables@v1
              with:
                path: .env
            - name: Set up Firefox
              uses: actions/setup-firefox@v1
              with:
                version: latest

            - name: install requirements
              run: pip install -r requirements.txt
            - name: run app
              run: python проход_по_группам_и_прожатие_участвоваеть.py
